[build]
  base = "main/client"
  publish = "main/client/dist"
  command = "npm run build"

[build.environment]
  VITE_API_BASE_URL = "https://api.acadmix.shop/api"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "*.mjs"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "*.jsx"
  [headers.values]
    Content-Type = "application/javascript"
